# Generated by Django 5.1 on 2024-11-15 10:25

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=1024, verbose_name='Латинское название [системное]')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='HTML текст')),
                ('comment', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Статические тексты',
                'ordering': ['id'],
            },
        ),
    ]
