# Generated by Django 5.1 on 2024-11-12 12:04

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название компании')),
                ('site_name', models.CharField(max_length=256, verbose_name='Название сайта')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Логотип')),
                ('title_text_index', models.CharField(blank=True, max_length=256, null=True, verbose_name='Заголовок текста на главной странице')),
                ('text_index', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст на главной странице')),
                ('text_category', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст (статический) в категории')),
                ('type_company', models.CharField(blank=True, max_length=256, null=True, verbose_name='Тип компании')),
                ('count_staff', models.CharField(blank=True, max_length=256, null=True, verbose_name='Количество сотрудников')),
                ('start_year', models.CharField(blank=True, max_length=50, null=True, verbose_name='Год основания')),
                ('text_head', models.TextField(blank=True, null=True, verbose_name='Блок в head (внизу)')),
                ('text_body', models.TextField(blank=True, null=True, verbose_name='Блок в body (внизу)')),
                ('tech_mail_server', models.CharField(max_length=256, verbose_name='Почтовый сервер (для отправки сообщений)')),
                ('tech_email', models.CharField(max_length=256, verbose_name='Почта для отправки сообщений')),
                ('tech_email_pass', models.CharField(max_length=256, verbose_name='Пароль почты для отправки сообщений')),
            ],
            options={
                'verbose_name_plural': 'Настройки проекта',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(default='', max_length=128, verbose_name='Название значка (css)')),
                ('name', models.CharField(max_length=1024, verbose_name='Ссылка')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Скрыть')),
                ('project_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_settings.projectsettings')),
            ],
        ),
    ]
