# Generated by Django 5.1 on 2024-11-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ф.И.О')),
                ('email', models.EmailField(blank=True, default='', max_length=50, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('type_order', models.CharField(default='', max_length=128, verbose_name='Тип')),
                ('type_client', models.CharField(default='', max_length=128, verbose_name='Клиент')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('email_to', models.EmailField(blank=True, default='', max_length=50, null=True, verbose_name='Отправлен')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date'],
            },
        ),
    ]
