# Generated by Django 5.1 on 2024-11-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='keywords_description',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='title_main',
        ),
        migrations.AlterField(
            model_name='offers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
    ]
