# Generated by Django 5.1 on 2024-11-22 08:32

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='О компании')),
                ('goal', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Цель компании')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Картинка')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Вторая Картинка')),
                ('is_hidden', models.BooleanField(blank=True, verbose_name='Скрыть')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'О компании',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Картинка')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Скрыть')),
                ('about_us', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_about_advantage', to='o_compania.about_us')),
            ],
            options={
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Скрыть')),
                ('about_us', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_about_principle', to='o_compania.about_us')),
            ],
            options={
                'verbose_name_plural': 'Принципы работы',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='Task_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Скрыть')),
                ('about_us', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_about_task', to='o_compania.about_us')),
            ],
            options={
                'verbose_name_plural': 'Задачи',
                'ordering': ['order_number'],
            },
        ),
    ]
