# Generated by Django 5.1 on 2024-11-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_compania', '0002_advantage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
