# Generated by Django 5.1 on 2024-11-22 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filials', '0001_initial'),
        ('o_compania', '0004_alter_advantage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('video', models.FileField(upload_to='videos/', verbose_name='Видео')),
                ('is_hidden', models.BooleanField(blank=True, verbose_name='Скрыть')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_review_filial', to='filials.filials', verbose_name='Филиал')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
                'ordering': ['order_number'],
            },
        ),
    ]
