# Generated by Django 5.1 on 2024-11-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_compania', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='image',
        ),
        migrations.AddField(
            model_name='about_us',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Первая картинка'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Картинка на главной'),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Вторая картинка'),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
