# Generated by Django 5.1 on 2024-12-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_compania', '0006_remove_about_us_image_about_us_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='video',
            field=models.CharField(max_length=1024, verbose_name='Ссылка на видео'),
        ),
    ]
