# Generated by Django 5.1 on 2024-11-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_bathroom_bedroom_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroom',
            name='number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Число санузлов'),
        ),
        migrations.AlterField(
            model_name='bedroom',
            name='number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Число спален'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Этажность'),
        ),
    ]
