# Generated by Django 5.1 on 2024-11-19 19:59

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название типа')),
                ('template', models.CharField(max_length=1024, verbose_name='Название файла шаблона')),
            ],
            options={
                'verbose_name_plural': 'Тип меню',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MenuCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название пункта')),
                ('name_title', models.CharField(blank=True, max_length=255, verbose_name='Название (в ед. числе)')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Название латинское')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('is_hide_marka', models.BooleanField(blank=True, verbose_name='Скрыть марку')),
                ('is_hide_standart', models.BooleanField(blank=True, verbose_name='Скрыть ГОСТ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Картинка')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание')),
                ('text_service', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст для карточки услуги')),
                ('flag_footer', models.BooleanField(verbose_name='Отображать в подвале')),
                ('flag_main', models.BooleanField(default=False, verbose_name='Отображать на главной')),
                ('title_main', models.CharField(blank=True, max_length=512, null=True, verbose_name='Заголовок страницы')),
                ('keywords', models.TextField(blank=True, help_text='Ключевые слова для SEO продвижения (через запятую). Мета тэг - keywords', null=True, verbose_name='Ключевые слова (мета)')),
                ('keywords_description', models.TextField(blank=True, help_text='Содержимое мета тэга - description', null=True, verbose_name='Описание (мета)')),
                ('has_child', models.BooleanField(default=False, editable=False, verbose_name='Есть вложенные категории')),
                ('is_hidden_child', models.BooleanField(default=False, verbose_name='Скрыть дочерние пункты')),
                ('is_hidden', models.BooleanField(verbose_name='Скрыть')),
                ('show_footer_left', models.BooleanField(default=False, verbose_name='Показывать в подвале (левый столбец)')),
                ('show_footer_rigth', models.BooleanField(default=False, verbose_name='Показывать в подвале (правый столбец)')),
                ('show_header_menu', models.BooleanField(default=False, verbose_name='Показывать в верхнем меню')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menucatalog', verbose_name='Родительский пункт')),
                ('parents', models.ManyToManyField(blank=True, db_table='MenuCatalog_and_parent_MenuCatalog', related_name='_id', to='menu.menucatalog', verbose_name='Добавить подкатегории')),
                ('region', models.ManyToManyField(blank=True, db_table='menucatalog_filials', to='filials.filials', verbose_name='Регионы')),
                ('uslugi', models.ManyToManyField(blank=True, db_table='MenuCatalog_and_uslugi_MenuCatalog', to='menu.menucatalog', verbose_name='Услуги')),
                ('type_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_menu', to='menu.typemenu', verbose_name='Тип меню')),
            ],
            options={
                'verbose_name_plural': 'Меню/Каталог',
                'ordering': ['order_number'],
            },
        ),
    ]
