# Generated by Django 5.1 on 2024-11-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucatalog',
            name='is_hide_marka',
        ),
        migrations.RemoveField(
            model_name='menucatalog',
            name='is_hide_standart',
        ),
        migrations.AddField(
            model_name='menucatalog',
            name='is_hide_marterial',
            field=models.BooleanField(blank=True, default=False, verbose_name='Скрыть Материал'),
        ),
    ]
