# Generated by Django 5.1 on 2024-11-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menucatalog_is_hide_marka_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucatalog',
            name='show_footer_left',
        ),
        migrations.RemoveField(
            model_name='menucatalog',
            name='show_footer_rigth',
        ),
        migrations.RemoveField(
            model_name='menucatalog',
            name='show_header_menu',
        ),
        migrations.RemoveField(
            model_name='menucatalog',
            name='text_service',
        ),
        migrations.RemoveField(
            model_name='menucatalog',
            name='uslugi',
        ),
    ]
