# Generated by Django 5.1 on 2024-11-26 18:39

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
        ('menu', '0003_remove_menucatalog_show_footer_left_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Название латинское')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Доп. параметры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Приоритет (Порядковый номер)')),
                ('name', models.CharField(max_length=1024, verbose_name='Название')),
                ('name_full', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Название ручное')),
                ('slug', models.SlugField(blank=True, max_length=1024, null=True, verbose_name='Название латинское')),
                ('param_1', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Этажность')),
                ('param_1_slug', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Этажность slug')),
                ('param_2', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Число спален')),
                ('param_2_slug', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Число спален slug')),
                ('param_3', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Число санузлов')),
                ('param_3_slug', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Число санузлов slug')),
                ('available', models.CharField(blank=True, max_length=128, null=True, verbose_name='Наличие')),
                ('ed_izm', models.CharField(blank=True, max_length=128, null=True, verbose_name='Единицы измерения')),
                ('price', models.CharField(blank=True, max_length=128, null=True, verbose_name='Базовая цена')),
                ('image', models.CharField(blank=True, max_length=256, null=True, verbose_name='Картинка основная')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание')),
                ('title_main', models.CharField(blank=True, max_length=512, null=True, verbose_name='Заголовок страницы')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Ключевые слова (мета)')),
                ('keywords_description', models.TextField(blank=True, null=True, verbose_name='Описание (мета)')),
                ('is_home', models.BooleanField(default=False, verbose_name='Показать на главной для хиты')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыть')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_catalog_set', to='menu.menucatalog', verbose_name='Каталог')),
                ('dop_param', models.ManyToManyField(blank=True, db_table='dop_param', related_name='dop_param_id', to='menu.additionalparam', verbose_name='Доп. параметры')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material', to='material.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name_plural': 'Дома',
                'ordering': ['catalog'],
            },
        ),
        migrations.CreateModel(
            name='PriceHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.PositiveIntegerField(verbose_name='Площадь дома')),
                ('ed_izm', models.CharField(blank=True, max_length=128, null=True, verbose_name='Единицы измерения')),
                ('price', models.CharField(blank=True, max_length=128, null=True, verbose_name='Цена/Материал')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house', to='menu.house', verbose_name='Дом')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_price', to='material.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name_plural': 'Доп. Цена',
            },
        ),
    ]
