# Generated by Django 5.1 on 2024-11-26 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_bathroom_bedroom_floor'),
        ('menu', '0004_additionalparam_house_pricehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='available',
        ),
        migrations.RemoveField(
            model_name='house',
            name='param_1',
        ),
        migrations.RemoveField(
            model_name='house',
            name='param_1_slug',
        ),
        migrations.RemoveField(
            model_name='house',
            name='param_2',
        ),
        migrations.RemoveField(
            model_name='house',
            name='param_2_slug',
        ),
        migrations.RemoveField(
            model_name='house',
            name='param_3',
        ),
        migrations.RemoveField(
            model_name='house',
            name='param_3_slug',
        ),
        migrations.AddField(
            model_name='house',
            name='bathrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_bathrom', to='material.bathroom', verbose_name='Число санузлов'),
        ),
        migrations.AddField(
            model_name='house',
            name='bedrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_bedrom', to='material.bedroom', verbose_name='Число спален'),
        ),
        migrations.AddField(
            model_name='house',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_floor', to='material.floor', verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='house',
            name='dop_param',
            field=models.ManyToManyField(blank=True, db_index=True, db_table='dop_param', related_name='dop_param_id', to='menu.additionalparam', verbose_name='Доп. параметры'),
        ),
        migrations.AlterField(
            model_name='house',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_material', to='material.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='pricehouse',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_house', to='menu.house', verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='pricehouse',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_material_price', to='material.material', verbose_name='Материал'),
        ),
    ]
