# Generated by Django 5.1 on 2024-11-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_additionalparam'),
        ('menu', '0006_alter_pricehouse_options_remove_house_ed_izm_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalParam',
        ),
        migrations.AlterField(
            model_name='house',
            name='dop_param',
            field=models.ManyToManyField(blank=True, db_index=True, db_table='dop_param', related_name='dop_param_id', to='material.additionalparam', verbose_name='Доп. параметры'),
        ),
    ]
