# Generated by Django 5.1 on 2024-11-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filials', '0001_initial'),
        ('menu', '0008_alter_house_is_hidden_alter_house_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucatalog',
            name='region',
            field=models.ManyToManyField(blank=True, db_index=True, db_table='menucatalog_filials', to='filials.filials', verbose_name='Регионы'),
        ),
    ]
