# Generated by Django 5.1 on 2024-12-10 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_additionalparam'),
        ('menu', '0009_alter_menucatalog_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='bathrom',
        ),
        migrations.RemoveField(
            model_name='house',
            name='bedrom',
        ),
        migrations.AddField(
            model_name='house',
            name='bathroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_bathroom', to='material.bathroom', verbose_name='Число санузлов'),
        ),
        migrations.AddField(
            model_name='house',
            name='bedroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_bedroom', to='material.bedroom', verbose_name='Число спален'),
        ),
    ]
