# Generated by Django 5.1 on 2024-12-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_house_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Базовая цена'),
        ),
    ]
