# Generated by Django 5.1 on 2024-12-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_alter_house_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehouse',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True, verbose_name='Цена/Материал'),
        ),
    ]
