# Generated by Django 5.1 on 2024-12-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_pricehouse_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['order_number', 'price', 'catalog'], 'verbose_name_plural': 'Дома'},
        ),
    ]
