# Generated by Django 5.1 on 2024-12-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_alter_house_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['catalog'], 'verbose_name_plural': 'Дома'},
        ),
    ]
