# Generated by Django 5.1 on 2024-12-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_alter_house_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image_2',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Картинка 2'),
        ),
        migrations.AddField(
            model_name='house',
            name='image_3',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Картинка 3'),
        ),
        migrations.AddField(
            model_name='house',
            name='image_4',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Картинка 4'),
        ),
        migrations.AddField(
            model_name='house',
            name='image_5',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Картинка 5'),
        ),
        migrations.AddField(
            model_name='house',
            name='image_6',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Картинка 6'),
        ),
    ]
